# build devcontainer and push to ghcr.io
on:
  workflow_dispatch: {}
  push: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout (GitHub)
      uses: actions/checkout@v3
          
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/hi5ato/codespace-devcontainer
        cacheFrom: ghcr.io/hi5ato/codespace-devcontainer
        push: filter
        refFilterForPush: "refs/heads/main"