# build devcontainer and push to ghcr.io
on:
  workflow_dispatch: {}
  push: {}
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout (GitHub)
      uses: actions/checkout@v3
          
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image base
      uses: devcontainers/ci@v0.3
      with:
        subFolder: base
        imageName: ghcr.io/hi5ato/codespace-devcontainer-base
        cacheFrom: ghcr.io/hi5ato/codespace-devcontainer-base
        push: filter
        refFilterForPush: "refs/heads/main"

    - name: Pre-build dev container image brew
      uses: devcontainers/ci@v0.3
      with:
        subFolder: with-brew
        imageName: ghcr.io/hi5ato/codespace-devcontainer
        cacheFrom: ghcr.io/hi5ato/codespace-devcontainer
        push: filter
        refFilterForPush: "refs/heads/main"